version: 2
jobs:
  build:
    working_directory: ~/passport-canvas
    docker:
      - image: node:8
        environment:
          NODE_ENV: test
    steps:
      - checkout

      - restore_cache:
          keys:
          - node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run:
          name: Install dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: node_modules-{{ checksum "package.json" }}-{{ checksum "package-lock.json" }}

      - run: npm test
      - run: npm run coverage

      - store_artifacts:
          path: coverage
